version: '3'
services:
  reactscratches:
    build: .
    # command: sh /loop/idle.shbased on [Syntax for a single-line Bash infinite while loop
](https://stackoverflow.com/questions/1289026/syntax-for-a-single-line-bash-infinite-while-loop)
    command: sh -c "while true; do echo 'Pause'; sleep 10; done"
    ports:
     - "8030:3000"
     - "8080:80"
    volumes:
     - .:/code
