version: '2'
services:
  electron:
    build: .
    ports:
      - "5000:5000"
    command: sh /code/idle.sh
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/code
