version: '2'
services:
  mynodered:
    build: .
    command: sh /codes/idle.sh
    # command: npm install
    ports:
     - "5000:5000"
     - "5901:5901"
     - "1880:1880"
    volumes:
     - .:/codes
     - /codes/node_modules
