version: '3'
services:
  gatsbyscratches:
    image: node
    command: node /idle/wait.js /idle/index.html
    ports:
     - "7080:8080"
     - "8080:8000"
    volumes:
     - .:/code
     - ../utilities:/idle
